# Generated by Django 4.2.3 on 2023-08-02 01:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_tax_payer', '0006_alter_taxpayer_tin'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarningLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('warningFor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_tax_payer.taxpayer')),
            ],
        ),
    ]
