# Generated by Django 4.2.4 on 2023-08-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warningletter',
            options={'ordering': ['-issued_date']},
        ),
    ]
