# Generated by Django 4.2.4 on 2023-08-02 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business')], default='individual', max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('nid', models.PositiveIntegerField(unique=True)),
                ('tin', models.PositiveIntegerField(unique=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Payer',
                'verbose_name_plural': 'Tax Payers',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_tax_payer.taxpayer')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTaxPaymentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_tax_payer.taxpayer')),
            ],
        ),
    ]
