# Generated by Django 4.2.3 on 2023-08-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_tax_payer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxpayer',
            name='email',
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='nid',
            field=models.PositiveIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
