# Generated by Django 4.2.3 on 2023-08-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_tax_payer', '0002_remove_taxpayer_email_taxpayer_nid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_tax_payer.taxpayer')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyTaxPaymentCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_tax_payer.taxpayer')),
            ],
        ),
    ]
