# Generated by Django 4.2.3 on 2023-08-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_tax_payer', '0004_taxpayer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='tin',
            field=models.PositiveIntegerField(default=None, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
