# Generated by Django 4.2.3 on 2023-08-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_tax_payer', '0005_taxpayer_tin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayer',
            name='tin',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
