# Generated by Django 4.2.3 on 2023-08-02 00:19

import App_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0002_remove_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100, validators=[App_auth.models.validate_password]),
        ),
    ]
